### ISSUE TITLE
Add option to unstar all starred repositories a user has

### ISSUE THREAD

**Issue by oscard0m** [octoherd/script-star-or-unstar#10]
Inspired by: https://github.com/tpkahlon/github-unstar

**Comment by gr2m** [comment]
Can you clarify what exactly the use case is? Unstar all repositories a user has access to? I don't think that would be an option for the script, but rather for the CLI to which we pass the repositories?

**Comment by oscard0m** [comment]
> Unstar all repositories a user has access to?
Unstar all repositories [a user has starred](https://docs.github.com/en/rest/reference/activity#list-repositories-starred-by-the-authenticated-user). 

Inspired by this script: https://github.com/tpkahlon/github-unstar/blob/4109bcfacfb6a81287659e84301bf4f368f81d57/index.js#L18

(fixed link of the repo I got inspired by in Issue description)

> I don't think that would be an option for the script, but rather for the CLI to which we pass the repositories?

I did not think about how to implement this but it's true it's something octoherd is not considering. Right now it is supported a certain repo or all the repos under a user/org. Maybe we can add this as a CLI flag?

**Comment by gr2m** [comment]
I think we already support it, you can set repositories to `*` to

```
  -R, --octoherd-repos            One or multiple repositories in the form of 'repo-owner/repo-n
                                  ame'. 'repo-owner/*' will find all repositories for one owner.
                                   '*' will find all repositories the user has access to. Will p
                                  rompt for repositories if not set.                     [array]
```

> '*' will find all repositories the user has access to.

Isn't that what you are looking for? You can run this script with `-R * --unstar` to achive the same thing as  https://github.com/tpkahlon/github-unstar does, unless I miss something?

**Comment by oscard0m** [comment]
> Isn't that what you are looking for? You can run this script with `-R * --unstar` to achive the same thing as https://github.com/tpkahlon/github-unstar does, unless I miss something?

`-R *` [is using](https://github.com/octoherd/cli/blob/1747357c13a836180a46480ea5e32bf7e8bf4841/lib/resolve-repositories.js#L70) [`GET /user/repos`](https://docs.github.com/en/rest/reference/repos) which returns:
> The authenticated user has explicit permission to access repositories they own, repositories where they are a collaborator, and repositories that they can access through an organization membership.

I think this list is different from the one provided by [`GET /user/starred`](https://docs.github.com/en/rest/reference/activity#list-repositories-starred-by-the-authenticated-user) right? You can star a repo without being a collaborator, an owner or not an organization member.

**Comment by gr2m** [comment]
> I think this list is different from the one provided by [`GET /user/starred`](https://docs.github.com/en/rest/reference/activity#list-repositories-starred-by-the-authenticated-user) right? You can star a repo without being a collaborator, an owner or not an organization member.

Ah yes, right! I get it now. I'd say that use case is out of scope for @octoherd, I don't see how we could make it work with the way the @octoherd CLI works today. We would need to implement some kind of custom logic to retrieve the list of repositories the script is run against I guess? I don't know, might be worth discussing in https://github.com/octoherd/cli?

**Comment by oscard0m** [comment]
> https://github.com/octoherd/cli

I think you are right and for now, let's keep it out scope. If we notice new needs similar to this one in the future, I will open that discussion and mention this issue.

**Comment by gr2m** [comment]
Just a random thought, but we would need to discuss that in https://github.com/octoherd/cli. Just want to put it out there :)

What do you think of this?

```
$ my-script-to-retrieve-repositories | npx @octoherd/script-star-or-unstar --unstar
```
